/home1/yanweicai/miniconda3/bin/python: Error while finding module specification for 'torch.distributed.launch' (ModuleNotFoundError: No module named 'torch')
/home1/yanweicai/miniconda3/envs/cv_env/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home1/yanweicai/miniconda3/envs/cv_env/bin/python: can't open file '/home1/yanweicai/workspace/prompt/grounding/prompt_grounding/tools/finetune_A.yaml': [Errno 2] No such file or directory
/home1/yanweicai/miniconda3/envs/cv_env/bin/python: can't open file '/home1/yanweicai/workspace/prompt/grounding/prompt_grounding/tools/finetune_A.yaml': [Errno 2] No such file or directory
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 30090) of binary: /home1/yanweicai/miniconda3/envs/cv_env/bin/python
Traceback (most recent call last):
  File "/home1/yanweicai/miniconda3/envs/cv_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home1/yanweicai/miniconda3/envs/cv_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home1/yanweicai/miniconda3/envs/cv_env/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home1/yanweicai/miniconda3/envs/cv_env/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home1/yanweicai/miniconda3/envs/cv_env/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home1/yanweicai/miniconda3/envs/cv_env/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home1/yanweicai/miniconda3/envs/cv_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home1/yanweicai/miniconda3/envs/cv_env/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/finetune_A.yaml FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-06_20:37:32
  host      : mk-SYS-7048GR-TR
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 30092)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-06_20:37:32
  host      : mk-SYS-7048GR-TR
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 30090)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
